### ISSUE TITLE
Fix syntax error in /root/.my.cnf

### ISSUE THREAD

**Issue by brmzkw** [scaleway-community/scaleway-redmine#9]
```
root@redmine:~# mysql
error: Found option without preceding group in config file: /root/.my.cnf at line: 1
Fatal error in defaults handling. Program aborted
```

The `[client]` section is missing.

**Comment by moul** [comment]
@brmzkw, about your complaining, this is something we will test with https://github.com/scaleway/qa/issues/3

You can already write some scripts somewhere in the repo so we can run the tests manually, I will then merge those tests on the QA tool

**Comment by brmzkw** [comment]
https://github.com/scaleway/image-tools/tree/test-mysql
